//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public string Subject { get; set; }
        public System.Guid EventId { get; set; }
        public System.Guid DoctorId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Description { get; set; }
    
        public virtual Dentist Dentist { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
